on:
  workflow_dispatch:
name: release-sunchirp-os
jobs:
  build-iso:
    name: Generate and Release ISOs
    runs-on: ubuntu-latest
    container:
      image: fedora:39
      options: --privileged
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Generate ISO
        uses: ublue-os/isogenerator@v2.2.0
        id: isogenerator
        with:
          image-name: ${{ github.event.repository.name }}
          installer-repo: releases
          installer-major-version: 39
          boot-menu-path: boot_menu.yml
      - name: Install GitHub CLI in Runner
        run: |
          sudo dnf install 'dnf-command(config-manager)' -y
          sudo dnf config-manager --add-repo https://cli.github.com/packages/rpm/gh-cli.repo
          sudo dnf install gh -y
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y%m%d')"
      - name: Create Release
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: |
          gh release create \
            39-${{ steps.date.outputs.date }} \
            --target main \
            --repo ${{ github.repository_owner }}/${{ github.event.repository.name }} \
            --notes 39-${{ steps.date.outputs.date }} \
            || true

      - name: Upload ISO
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: |
          gh release upload \
            39-${{ steps.date.outputs.date }} \
            ./${{ steps.isogenerator.outputs.iso-path }} \
            --repo ${{ github.repository_owner }}/${{ github.event.repository.name }} \
            --clobber

      - name: Upload SHA256SUM
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: |
          gh release upload \
            39-${{ steps.date.outputs.date }} \
            ./${{ steps.isogenerator.outputs.sha256sum-path }} \
            --repo ${{ github.repository_owner }}/${{ github.event.repository.name }} \
            --clobber
